version: 0.2
env:
  variables:
    taito_mode: "ci"

phases:
  pre_build:
    commands:
      # Determine ENV and IMAGE_TAG
      - export ENV=$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }' | xargs echo $CODEBUILD_WEBHOOK_HEAD_REF | awk '{ printf $1 }' | sed 's/.*\///')
      - export IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      # TODO: Cancel other ongoing builds for $ENV
      # - taito deployment cancel:$ENV $CURRENT_BUILD_ID
      # Prepare build
      - taito build prepare:$ENV $IMAGE_TAG
  build:
    commands:
      # Prepare artifacts for deployment (TODO: can be executed parallel)
      - taito artifact prepare:www:$ENV $IMAGE_TAG
      - taito artifact prepare:webhook:$ENV $IMAGE_TAG false ./www ./www Dockerfile.webhook
      # Deploy changes to target environment
      - taito deployment deploy:$ENV $IMAGE_TAG
      # Test and verify deployment
      - taito deployment wait:$ENV
      - taito test:$ENV
      - taito deployment verify:$ENV
      # Release artifacts (TODO: can be executed parallel)
      - taito artifact release:www:$ENV $IMAGE_TAG
      - taito artifact release:webhook:$ENV $IMAGE_TAG
      # Release build
      - taito build release:$ENV
