# NOTE: docker-compose taito plugin sets DC_PATH and DC_COMMAND to mitigate
# slow volume mounts on Windows. They might also be used in some other purposes
# in the future.

version: '3.5'
services:
  website-template-www:
    container_name: website-template-www
    build:
      context: ./www
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9999:8080"
    volumes:
      - "./www:${DC_PATH}/service:delegated"
      - "${DC_PATH}/service/node_modules"
      - "${DC_PATH}/service/site/node_modules" # FOR GATSBY ONLY
      # FOR GATSBY ONLY:
      # - "${DC_PATH}/service/site/node_modules"
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_PUBLIC_PORT: 9999

  # NOTE: For testing build webhook locally
  # website-template-webhook:
  #   container_name: website-template-webhook
  #   build:
  #     context: ./www
  #     dockerfile: Dockerfile.webhook
  #   restart: unless-stopped
  #   networks:
  #     - default
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     HOST_UNAME: ${taito_host_uname}
  #     COMMON_PUBLIC_PORT: 9999
  #     COMMON_ENV: dev
  #     VC_REPOSITORY_URL: github.com/TaitoUnited/website-template.git
  #     WEBHOOK_URL_PREFIX: SECRET
  #     WEBHOOK_VC_TOKEN: SECRET

networks:
  default:
