# This file is used to run your application locally with Docker Compose

version: '3.8'
services:
  website-template-www:
    container_name: website-template-www
    build:
      context: ./www
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:9999:8080"
      - "127.0.0.1:4229:9229"
    volumes:
      - "./www:/develop:delegated"
      - "/develop/node_modules"
      - "/develop/site/node_modules" # FOR GATSBY ONLY
      # FOR GATSBY ONLY:
      # - "/develop/site/node_modules"
    environment:
      HOST_OS: ${taito_host_os}
      COMMON_PUBLIC_PORT: 9999
      BASE_PATH: ''
      ASSETS_PATH: ''
      ASSETS_DOMAIN: ''

  # NOTE: For testing build webhook locally
  # website-template-webhook:
  #   container_name: website-template-webhook
  #   build:
  #     context: ./www
  #     dockerfile: Dockerfile.webhook
  #   restart: unless-stopped
  #   networks:
  #     - default
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "./www:/develop:delegated"
  #     - "/develop/node_modules"
  #     - "/develop/site/node_modules"
  #   secrets:
  #     - WEBHOOK_URL_PREFIX
  #     - SLACK_WEBHOOK_URL
  #     - VC_TOKEN
  #   environment:
  #     HOST_OS: ${taito_host_os}
  #     COMMON_PUBLIC_PORT: 9754
  #     COMMON_ENV: dev
  #     WEBSITE_URL: http://localhost:9754
  #     SLACK_CHANNEL: taito-website
  #     # OPTIONAL:
  #     VC_PULL_ENABLED: 'false'
  #     VC_REPOSITORY_URL: ${taito_vc_repository_url}.git

# NOTE: For testing build webhook locally
# secrets:
#   WEBHOOK_URL_PREFIX:
#     file: ./secrets/${taito_env}/${taito_project}-${taito_env}-webhook.urlprefix
#   SLACK_WEBHOOK_URL:
#     file: ./secrets/${taito_env}/${taito_project}-${taito_env}-webhook.slackurl
#   VC_TOKEN:
#     file: ./secrets/${taito_env}/${taito_project}-${taito_env}-webhook.gittoken

networks:
  default:
